repos:
 - repo: https://github.com/Quantco/pre-commit-mirrors-black
   rev: 22.3.0
   hooks:
     - id: black-conda
       args:
         - --safe
         - --target-version=py37
       exclude: ^src/pytsql/grammar/
 - repo: https://github.com/Quantco/pre-commit-mirrors-flake8
   rev: v3.8.4
   hooks:
    - id: flake8-conda
      exclude: ^src/pytsql/grammar/
 - repo: https://github.com/Quantco/pre-commit-mirrors-isort
   rev: 5.6.4
   hooks:
    - id: isort-conda
      additional_dependencies: [toml]
      exclude: ^src/pytsql/grammar/
 - repo: https://github.com/Quantco/pre-commit-mirrors-mypy
   rev: "0.961"
   hooks:
    - id: mypy-conda
      additional_dependencies: [ -c, conda-forge, types-setuptools ]
      exclude: ^src/pytsql/grammar/
 - repo: https://github.com/Quantco/pre-commit-mirrors-pyupgrade
   rev: 2.7.2
   hooks:
    - id: pyupgrade-conda
      exclude: ^src/pytsql/grammar/
      args:
          - --py37-plus
