repos:
 - repo: https://github.com/Quantco/pre-commit-mirrors-black
   rev: 23.10.1
   hooks:
     - id: black-conda
       args:
         - --safe
         - --target-version=py38
       exclude: ^src/pytsql/grammar/
 - repo: https://github.com/Quantco/pre-commit-mirrors-ruff
   rev: 0.1.3
   hooks:
    - id: ruff-conda
      exclude: ^src/pytsql/grammar/
 - repo: https://github.com/Quantco/pre-commit-mirrors-mypy
   rev: "1.6.1"
   hooks:
    - id: mypy-conda
      additional_dependencies: [ -c, conda-forge, types-setuptools ]
      exclude: ^src/pytsql/grammar/
