repos:
 - repo: https://github.com/Quantco/pre-commit-mirrors-black
   rev: 20.8b1
   hooks:
     - id: black-conda
       args:
         - --safe
         - --target-version=py36
       exclude: ^src/pytsql/grammar/
 - repo: https://github.com/Quantco/pre-commit-mirrors-flake8
   rev: v3.8.4
   hooks:
    - id: flake8-conda
      additional_dependencies: [flake8-docstrings, flake8-rst-docstrings]
      exclude: ^src/pytsql/grammar/
 - repo: https://github.com/Quantco/pre-commit-mirrors-isort
   rev: 5.6.4
   hooks:
    - id: isort-conda
      additional_dependencies: [toml]
      exclude: ^src/pytsql/grammar/
 - repo: https://github.com/Quantco/pre-commit-mirrors-mypy
   rev: "0.790"
   hooks:
    - id: mypy-conda
      additional_dependencies: [ mypy=0.800, python=3.7.9 ]
      exclude: ^src/pytsql/grammar/
 - repo: https://github.com/Quantco/pre-commit-mirrors-pyupgrade
   rev: 2.7.2
   hooks:
    - id: pyupgrade-conda
      exclude: ^src/pytsql/grammar/
