exclude: (^\.pixi)|(^src\/pytsql\/grammar\/)
repos:
  - repo: local
    hooks:
      # ensure pixi environments are up to date
      # workaround for https://github.com/prefix-dev/pixi/issues/1482
      - id: pixi-install
        name: pixi-install
        entry: pixi install -e default -e lint
        language: system
        always_run: true
        require_serial: true
        pass_filenames: false
      - id: ruff
        name: ruff
        entry: pixi run -e lint ruff check --fix --exit-non-zero-on-fix --force-exclude
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: black-conda
        name: black-conda
        entry: pixi run -e lint black
        language: system
        require_serial: true
        types: [python]
      - id: mypy
        name: mypy
        entry: pixi run -e default mypy
        language: system
        types: [python]
        args: ["--ignore-missing-imports", "--scripts-are-modules"]
        require_serial: true
