name: pytsql
channels:
  - conda-forge
  - nodefaults
dependencies:
  - setuptools_scm
  - pre-commit
  - pytest
  - pytest-mock
  - pytest-cov
  - make
  - numpydoc
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-apidoc
  - sqlalchemy>=1.4
  - pyodbc
  - speedy-antlr-tool==1.4.1
  - antlr4-python3-runtime==4.11.1
  - click
