name: pytsql
channels:
  - quantco_main
  - conda-forge
  - nodefaults
dependencies:
  - pre-commit
  - pytest
  - pytest-mock
  - pytest-cov
  - make
  - numpydoc
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-apidoc
  - sqlalchemy
  - antlr4-python3-runtime =4.9.2
  - freetds
  - msodbcsql17
  - pyodbc
