name: pytsql
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.8
  - setuptools_scm
  - pre-commit
  - pytest
  - pytest-mock
  - pytest-cov
  - make
  - numpydoc
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-apidoc
  - sqlalchemy>=1.4
  - pyodbc
  - speedy-antlr-tool==1.4.3
  - antlr4-python3-runtime==4.13.1 # keep `.github/workflows/update_grammar.yml` in sync
  - click
  - openjdk
