[project]
name = "pytsql"
channels = ["conda-forge", "nodefaults"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[tasks]
postinstall = "pip install --no-build-isolation --no-deps --disable-pip-version-check -e ."
integration-test = "pytest --backend=mssql tests/integration"

[dependencies]
python = ">=3.9"
sqlalchemy = ">=1.4, <3"
pyodbc = ">=4.0.30"
antlr4-python3-runtime = ">=4.10,<4.14"
click = "*"

[host-dependencies]
pip = "*"
setuptools-scm = "*"
compilers = "*"

[feature.test.dependencies]
pytest = "*"
pytest-mock = "*"
pytest-cov = "*"
mypy = "*"

[feature.docs.dependencies]
make = "*"
numpydoc = "*"
sphinx = "*"
sphinx_rtd_theme = "*"
sphinxcontrib-apidoc = "*"

[feature.lint.dependencies]
pre-commit = "*"
ruff = "*"
pre-commit-hooks = "*"
typos = "*"
taplo = "*"

[feature.lint.tasks]
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run -a"

[feature.grammar.dependencies]
openjdk = "*"
speedy-antlr-tool = "1.4.3"
[feature.grammar.tasks]
update-grammar = "cd ./src/pytsql/grammar/ && ./helper_generate_grammar_targets.sh antlr4-4.13.1-complete.jar -d"

[feature.py39.dependencies]
python = "3.9.*"
[feature.py310.dependencies]
python = "3.10.*"
[feature.py311.dependencies]
python = "3.11.*"
[feature.py312.dependencies]
python = "3.12.*"
[feature.py313.dependencies]
python = "3.13.*"

[feature.antlr410.dependencies]
antlr4-python3-runtime = "4.10.*"
[feature.antlr411.dependencies]
antlr4-python3-runtime = "4.11.*"
[feature.antlr412.dependencies]
antlr4-python3-runtime = "4.12.*"
[feature.antlr413.dependencies]
antlr4-python3-runtime = "4.13.*"

[feature.sa1.dependencies]
sqlalchemy = ">=1.4,<2"
[feature.sa2.dependencies]
sqlalchemy = "2.*"

[environments]
default = ["test"]
py39 = ["py39", "test"]
py310 = ["py310", "test"]
py311 = ["py311", "test"]
py312 = ["py312", "test"]
py313 = ["py313", "test"]
antlr410 = ["antlr410", "test"]
antlr411 = ["antlr411", "test"]
antlr412 = ["antlr412", "test"]
antlr413 = ["antlr413", "test"]
sa1 = ["sa1", "test"]
sa2 = ["sa2", "test"]

lint = { features = ["lint"], no-default-feature = true }

docs = ["docs"]

grammar = ["grammar"]
