[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pytsql"
authors = [{name = "Kevin Klein", email = "kevin.klein@quantco.com"}]
maintainers = [{name = "Kevin Klein", email = "kevin.klein@quantco.com"}]
keywords = []
classifiers = []
readme = "README.md"
dynamic = ["version", "description"]

requires-python = ">=3.7"

dependencies = [
    "sqlalchemy >=1.4",
    "pyodbc",
]

[project.urls]
Source = "https://github.com/quantco/pytsql"


[tool.black]
exclude = '''
/(
    \.eggs
  | \.git
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
ensure_newline_before_comments = true
line_length = 88
known_first_party = "pytsql"
skip_glob = '\.eggs/*,\.git/*,\.venv/*,build/*,dist/*'
default_section = 'THIRDPARTY'