name: CI
on: [push]

jobs:
  linux:
    name: "Linux - unit tests - Python ${{ matrix.PYTHON_VERSION }}"
    runs-on: ubuntu-latest
    env:
      CI: True
    strategy:
      fail-fast: true
      matrix:
        PYTHON_VERSION: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2.3.5
        with:
          ref: ${{ github.head_ref }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
          miniforge-variant: Mambaforge
          miniforge-version: 4.11.0-2
          use-mamba: true
          environment-file: environment.yml
          activate-environment: pytsql
      - name: Run Unit Tests
        shell: bash -l {0}
        run: |
          flit install -s
          pytest tests/unit

  linux-integration_tests-sqlserver:
    name: "Linux - integration tests - Python ${{ matrix.PYTHON_VERSION }} - SQL server with ${{ matrix.DRIVER }} driver"
    runs-on: ubuntu-latest
    env:
      CI: True
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ['3.8']
        DRIVER: ["mssql"] #, "mssql-freetds"]
    services:
      DB:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: QuantCo@MSSQL
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Fetch full git history
        run: git fetch --prune --unshallow
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}
          miniforge-variant: Mambaforge
          miniforge-version: 4.11.0-2
          use-mamba: true
          environment-file: environment.yml
          activate-environment: pytsql
      - name: Run Unit Tests
        shell: bash -l {0}
        env:
          DB_ADDR: DB:1433
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -

          curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list > /etc/apt/sources.list.d/mssql-release.list

          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17
          flit install -s
          pytest --backend=${{ matrix.DRIVER }} tests/integration
